services:
  rag_app:
    build: ./rag_app
    env_file:
      - .env
    networks:
      - rag_network
    ports:
      - 8501:8501
    volumes:
      - ./rag_app:/app 
    command: streamlit run run_app_streamlit_ui.py
    

  rag_database:
    image: agnohq/pgvector:16
    env_file:
      - .env
    networks:
      - rag_network
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - 5532:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  rag_network:
    driver: bridge

volumes:
  pgvolume:
    driver: local